require 'pachube_data_formats/templates/xml_headers'
require 'pachube_data_formats/templates/helpers'
require 'pachube_data_formats/templates/json/feed_defaults'
require 'pachube_data_formats/templates/json/datastream_defaults'
require 'pachube_data_formats/templates/json/datapoint_defaults'
require 'pachube_data_formats/templates/json/search_result_defaults'
require 'pachube_data_formats/templates/xml/feed_defaults'
require 'pachube_data_formats/templates/xml/datastream_defaults'
require 'pachube_data_formats/templates/xml/datapoint_defaults'
require 'pachube_data_formats/templates/xml/search_result_defaults'

