require 'pachube_data_formats/parsers/json/feed_defaults'
require 'pachube_data_formats/parsers/json/search_result_defaults'
require 'pachube_data_formats/parsers/json/datastream_defaults'
require 'pachube_data_formats/parsers/json/datapoint_defaults'
require 'pachube_data_formats/parsers/json/trigger_defaults'
require 'pachube_data_formats/parsers/json/key_defaults'
require 'pachube_data_formats/parsers/json/app_defaults'
require 'pachube_data_formats/parsers/xml/feed_defaults'
require 'pachube_data_formats/parsers/xml/datastream_defaults'
require 'pachube_data_formats/parsers/xml/datapoint_defaults'
require 'pachube_data_formats/parsers/xml/trigger_defaults'
require 'pachube_data_formats/parsers/xml/key_defaults'
require 'pachube_data_formats/parsers/xml/app_defaults'
require 'pachube_data_formats/parsers/csv/feed_defaults'
require 'pachube_data_formats/parsers/csv/datastream_defaults'

